# -*- coding: utf-8 -*-
"""Introducción a Python .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MszrPcH-UkdNx0hGtkD8eCtnjJ6icMMC

# Introducción a Python 

 

## Python

Python es un lenguaje de programación usado en ciencias e ingeniería. Es ideal para aprender programación porque su sintáxis es simple y es un lenguaje muy popular en este momento. 

Python permite crear programas que resuelvan problemas automatizando tareas repetitivas, procesando grandes cantidades de datos, resolviendo complejos cálculos matemáticos, o simplemente, creando visualizaciones de fenónenos complejos.

Recuerda que programar significa darle instrucciones al computador para que haga lo que yo quiera. Podemos comenzar por pedirle que imprima "hola Mundo"
"""

print("Mi primer hola mundo")

"""### Actividad 1

Lo que hicimos fue simplemente decirle al computador que imprimiera (print) el texto que estaba entre las comillas. Escribe una instrucción para imprimir otro mensaje en el siguiente espacio y luego ejecutalo. coloca 5 datos personales


"""

print("Mi nombre es Heyner: ")
print("Mi Apellido es Cabarcas :")
print("tel 30157431..... ")
print("Mi correo es ing_heiner@misena.edu.co....")

"""### Actividad 2
Vamos a modificar el siguiente algoritmo para escribirlo en Python. 

Inicio

    uno ⇐ 5
    dos ⇐ 8
    tres ⇐ 3

    total =  uno + dos
Fin
"""

uno = 10
dos = 1
tres = 5
 
total =  uno + dos + tres

"""Por ahora no vemos nada, pero qué tal si imprimirmos la variable total? Ingresa el código para imprimir la variable total"""

total

"""Y si quisieramos leer el valor? Python cuenta con la función input() para leer valores. """

valor_uno = float(input())
valor_dos = float(input())
print(valor_uno + valor_dos)

"""En el código anterior además de la función input() usamos float() para determinar el tipo de dato. Por defecto, Python leería la variable como una cadena de caracteres, pero para poder realizar operaciones aritméticas, necesitamos identificarlas como número. En este caso, float quiere decir flotante. Más adelante analizaremos otros tipos de datos.

Ahora revisemos los operadores aritméticos y su sintáxis en Python

<table>
<thead><tr>
<th>Operador</th>
<th>Nombre</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>a + b</code></td>
<td>Suma</td>
<td>Suma de <code>a</code> y <code>b</code></td>
</tr>
<tr>
<td><code>a - b</code></td>
<td>Resta</td>
<td>Diferencia entra <code>a</code> y <code>b</code></td>
</tr>
<tr>
<td><code>a * b</code></td>
<td>Multiplicación</td>
<td>Multiplicación de <code>a</code> y <code>b</code></td>
</tr>
<tr>
<td><code>a / b</code></td>
<td>División real</td>
<td>Resultado de <code>a</code> dividido <code>b</code></td>
</tr>
<tr>
<td><code>a // b</code></td>
<td>División con redondeo</td>
<td>Resultado de <code>a</code> dividido b <code>b</code>, redondeo a número entero</td>
</tr>
<tr>
<td><code>a % b</code></td>
<td>Modulo</td>
<td>Residuo de la división entre <code>a</code> y <code>b</code></td>
</tr>
<tr>
<td><code>a ** b</code></td>
<td>Potencia</td>
<td><code>a</code> a la potencia de <code>b</code></td>
</tr>
<tr>
<td><code>-a</code></td>
<td>Negación</td>
<td>Negativo de <code>a</code></td>
</tr>
</tbody></table>

Observemos la diferencia entre división real y división con redondeo en Python.
"""

print(6/2)
print(5/2)

print(6//2)
print(5//2)

"""### Actividad 3

Escribe un programa que pregunte al usuario por el número de horas trabajadas y el costo por hora. Después debe mostrar por pantalla el pago que le corresponde

"""

horas = float(input("Introduce tus horas de trabajo: "))
costo = float(input("Introduce lo que cobras por hora: "))
paga = horas * costo
print("Tu pago es", paga)

"""### Actividad 4
Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable, y muestre por pantalla la frase Tu índice de masa corporal es <imc> donde <imc> es el índice de masa corporal calculado redondeado con dos decimales.
"""

peso = input("¿Cuál es tu peso en kg? ")
estatura = input("¿Cuál es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("Tu índice de masa corporal es " + str(imc))

"""### Actividad 5
Una juguetería tiene mucho éxito en dos de sus productos: payasos y muñecas. Suele hacer venta por correo y la empresa de logística les cobra por peso de cada paquete así que deben calcular el peso de los payasos y muñecas que saldrán en cada paquete a demanda. Cada payaso pesa 112 g y cada muñeca 75 g. Escribir un programa que lea el número de payasos y muñecas vendidos en el último pedido y calcule el peso total del paquete que será enviado.
"""

peso_payaso = 112
peso_muñeca = 75
payasos = int(input("Introduce el número de payasos a enviar: "))
muñecas = int(input("Introduce el número de muñecas a enviar: "))
peso_total = peso_payaso * payasos + peso_muñeca * muñecas
print("El peso total del paquete es " + str(peso_total))