# -*- coding: utf-8 -*-
"""Introducción a Python .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1puahiVBmVDiA8uoLfC14zfO8t4ruoXdK

# Programación con Python - Condicionales

La sintaxis de la construcción if es la siguiente:

if condición:
    aquí van las órdenes que se ejecutan si la condición es cierta
    y que pueden ocupar varias líneas
    
Recuerda que los condicionales múltiples y anidados nos permiten evaluar múltiples casos. 
El condicional Si-Sino-Si-Finsi tiene la siguiente estructura:

    Si (condición) Entonces
        instrucción(es)
    Sino Si
        instrucción(es)
    Fin Si
  
En Python, esto se escribe un poco diferente y la estructura general depende de las tabulaciónes.

### Actividad 1

Ingresar un numero por consola y determinar si es positivo o negativo, validar el cero
"""

x = int(input("Por favor ingresa un número: "))
if x < 0:
        print('El número es Negativo')
elif x > 0:
        print('El número es positivo')
elif x == 0:
        print('El número es cero')

"""### Actividad 2
Escribir un programa que pida al usuario un número entero y muestre por pantalla si es par o impar.
"""

n = int(input("Introduce un número entero: "))
if n % 2 == 0:
    print("El número " + str(n) + " es par")
else:
    print("El número " + str(n) + " es impar")

"""### Actividad 3

Escribe el código para dos numeros a y b, el usuario va a seleccionar una opcion: 
       #1 para sumar, 2 para multiplicar, 3 para restar (a-b) y 4 para dividir (a/b) y 
        #retornar el resultado de la operación indicada.

"""

a = int(input("Ingrese el primer número (a): "))
b = int(input("Ingrese el segundo número (b): "))
opcion = int(input("Ingrese la opcion (1 para sumar, 2 para multiplicar, 3 para restar (a-b) y 4 para dividir (a/b)): "))
    #Escribe el código para dos numeros a y b, el usuario va a seleccionar una opcion: 
        #1 para sumar, 2 para multiplicar, 3 para restar (a-b) y 4 para dividir (a/b) y 
        #retornar el resultado de la operación indicada.
if opcion == 1:
        total = a+b
elif opcion == 2:
        total = a*b
elif opcion == 3:
        total = a-b
elif opcion == 4:
        total = a/b

print("Resultado "+ str(total))

"""### Actividad 4

Para tributar un determinado impuesto se debe ser mayor de 16 años y tener unos ingresos superiores a 1000 € mensuales. Escribir un programa que pregunte al usuario su edad y sus ingresos mensuales y muestre por pantalla si el usuario tiene que tributar o no.
"""

age = int(input("¿Cuál es tu edad? "))
income = float(input("¿Cuales son tus ingresos mensuales?"))
if age > 16 and income >= 1000:
    print("Tienes que cotizar")
else:
    print("No tienes que cotizar")

"""Actividad 5

leer tres valores y almacenarlos en las variables A, B y C respectivamente. El algoritmo debe imprimir cual es el mayor
"""

A=int(input("ingrese un numero\n"))
B=int(input("ingrese otro numero\n"))
C=int(input("ingrese un nuemero\n"))
if(A > B and A > C):
 print("El numero mayor es " + str(A))
else:
 if(B > A and B > C):
  print("El numero mayor es " + str(B))
 else:
  print("El numero mayor es " + str(C))