# -*- coding: utf-8 -*-
"""Introducción a Python .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1puahiVBmVDiA8uoLfC14zfO8t4ruoXdK

# Programación con Python - Ciclos Repetitivos 


El ciclo Para o For en Python nos ayuda a ejecutar dentro dentro de un rango determinado de iteraciones. 
Esto es particularmente útil cuando usamos estructuras de datos que son inherentement "ordenadas"; listas, colecciones, cadenas de caracteres, etc.

### Actividad 1

Escribir un programa que pida al usuario una palabra y la muestre 10 veces por pantalla.
"""

word = input("Introduce una palabra: ")
for i in range(10):
    print(word)

"""### Actividad 2
Escribe un algoritmo que lea 10 números e imprima cuantos son pares y impares, neutros(0).
"""

pares = 0
impares = 0
neutro = 0
for i in range(5):
  num = int(input("Ingresa un número: "))
  if num == 0:
      neutro += 1
  elif num%2 == 0:
      pares += 1
  else:
      impares += 1
    
print("Pares: "+ str(pares))
print("Impares: "+ str(impares))
print("Neutros: "+ str(neutro))

"""### Actividad 3

Escribe un algoritmo que lea 10 números e imprima cuantos son positivos, negativos y neutros(0)

"""

positivos = 0
negativos = 0
neutro = 0
for i in range(5):
  num = int(input("Ingresa un número: "))
  if num == 0:
      neutro += 1
  elif num%2 == 0:
      positivos += 1
  else:
      negativos += 1
    
print("Positivos: "+ str(positivos))
print("Negativos: "+ str(negativos))
print("Neutros: "+ str(neutro))

"""Un bucle while permite repetir la ejecución de un grupo de instrucciones mientras se
cumpla una condición (es decir, mientras la condición tenga el valor True).

### Actividad 4 Ciclo - While

Leer números enteros de teclado, hasta que el usuario ingrese el 0. Finalmente, mostrar la sumatoria de todos los números ingresados
"""

total=0
nro=int(input("Número: "))
while nro != 0:
    total+=nro
    nro=int(input("Número: "))
print(total)

"""Actividad 5

Elaborar un ejercicio que pida un número al usuario, e imprima todos los números pares desde 2 hasta el número. 
"""

numero = int(input("Ingresa un número: "))
i = 2
while i < numero:
  print(i)
  i += 2